defaults: &defaults
  amqp:
    hosts: [localhost]
    port: 5672
    vhost: /
    user: email_alert_service
    pass: email_alert_service
    recover_from_connection_close: true

development:
  <<: *defaults
  exchange: published_documents
  queues:
    - processor: major_change_message_processor
      name: email_alert_service
      routing_key: '*.major.#'
    - processor: unpublishing_message_processor
      name: email_unpublishing
      routing_key: 'redirect.unpublishing.#'
    - processor: workflow_message_processor
      name: email_alert_service_workflow
      routing_key: "*.workflow.#"

test:
  <<: *defaults
  amqp:
    user: email_alert_service_test
    pass: email_alert_service_test
  exchange: email_alert_service_published_documents_test_exchange
  queues:
    - processor: major_change_message_processor
      name: email_alert_service_published_documents_test_queue
      routing_key: "*.major.#"
    - processor: unpublishing_message_processor
      name: email_alert_service_unpublishing_documents_test_queue
      routing_key: "redirect.unpublishing.#"
    - processor: workflow_message_processor
      name: email_alert_service_workflow_test_queue
      routing_key: "*.workflow.#"

production:
  <<: *defaults
  amqp:
    hosts:
      <% hosts = ENV['RABBITMQ_HOSTS'] || 'localhost' %>
      <% hosts.split(",").each do |host| %>
      - <%= host %>
      <% end %>
    user: <%= ENV['RABBITMQ_USER'] %>
    pass: <%= ENV['RABBITMQ_PASSWORD'] %>
    recover_from_connection_close: true
  exchange: <%= ENV['RABBITMQ_EXCHANGE'] || 'published_documents' %>
  queues:
    - processor: major_change_message_processor
      name: <%= ENV['RABBITMQ_QUEUE'] || 'email_alert_service' %>
      routing_key: "*.major.#"
    - processor: unpublishing_message_processor
      name: email_unpublishing
      routing_key: "redirect.unpublish.#"
    - processor: workflow_message_processor
      name: <%= ENV['RABBITMQ_QUEUE'] || 'email_alert_service_workflow' %>
      routing_key: "*.workflow.#"

